<%@ Page Title="" Language="C#" MasterPageFile="~/master.Master" AutoEventWireup="true" CodeBehind="chat.aspx.cs" Inherits="frilansa.WebForm1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        #chat {
            width: 50%;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 2em;
            padding-bottom: 2em;
            margin-bottom: 2em;
            padding-bottom: 2em;
            text-align: center;
        }

.others {
    background-color: lightblue;
    border-radius : 1em;
    padding: 0.3em;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    -moz-border-radius: 1em;
    -webkit-border-radius: 1em;
    width: 50%;
                margin-left: auto;
            margin-right: auto;
}

.caller {

    background-color: lightcoral;
    border-radius : 1em;
    padding: 0.3em;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    -moz-border-radius: 1em;
    -webkit-border-radius: 1em;
      width: 50%;
                  margin-left: auto;
            margin-right: auto;

   
}

@media (max-width: 900px ) {
    #container {
        width: 100%;
    }

    .caller, .others {
        width: 100%;
    }
}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="content">
        <div class="image">
            <img src="Images/people.jpg" />
        </div>
        <h1 class="center">Live chatt</h1>
        <div id="chat">
            <div id="activeUsers" style="display: none"></div>
            <div id="users">
                <div id="displayname"></div>
                <span>Inloggade: </span>
                <span id="hitCountValue">0</span>
                <span>användare</span><br />
                <div id="chatUsers"></div>
            </div>

            <input type="text" id="message" />
            <input type="button" id="sendmessage" value="Send" /><br/>
            <div id="chatMessages"></div>
        </div>
    </div>
    <!--Script references. -->
        <!--Reference the jQuery library. -->
        <script src="Scripts/jquery-1.10.2.min.js"></script>
        <!--Reference the SignalR library. -->
        <script src="Scripts/jquery.signalR-2.0.0.min.js"></script>
        <!--Reference the autogenerated SignalR hub script. -->
        <script src="signalr/hubs"></script>
        <!--Add script to update the page and send messages.-->
        <script src="Scripts/jquery.js" type="text/javascript">
        </script>
</asp:Content>
